### ISSUE TITLE
有点没搞懂怎么导入或者编辑ssr和ssrot的服务器

### ISSUE THREAD

**Issue by zyp997** [winXray/winXray#1]
RT.或者说是可以给个json格式吗？

**Comment by yfdyh000** [comment]
配置-服务器配置-右键菜单。

**Comment by zyp997** [comment]
@yfdyh000  protocol参数提示，没有ssr和ssrot的选项，只有vmess、vless、Trojan、Trojan-go、ss的。

**Comment by winXray** [comment]
直接复制 ssr 或 ssrot 的分享链接、订阅链接都可以，
然后点击【批量导入链接】
![image](https://user-images.githubusercontent.com/76848066/104546910-2eff4180-5668-11eb-89ba-b9e6e92e5e33.png)

或者右键点 winXray 首页服务器列表（或空白处）
然后点击【新增服务器配置】
![image](https://user-images.githubusercontent.com/76848066/104546991-5fdf7680-5668-11eb-86b7-5f1ec3a54f76.png)

代理协议下拉框里肯定是有SSR的（没有你可能是没有升级到3.0）
![image](https://user-images.githubusercontent.com/76848066/104547038-82718f80-5668-11eb-9b2c-3cf99c16b9a5.png)

SSRoT 只是参数不一样，但是你并不需要专门去学习，
winXray 已经把不同代理协议的字段名都统一了，例如 SSRoT 里的 ot_enable，你仍然可以跟v2ray 一样，写 tls="tls" 就可以了，不同的写法，winXray 会自动转换。

**Comment by winXray** [comment]
![image](https://user-images.githubusercontent.com/76848066/104547242-0461b880-5669-11eb-8766-bf8a6d2cbeb5.png)

![image](https://user-images.githubusercontent.com/76848066/104547261-12173e00-5669-11eb-8f9f-36c44e7256ca.png)

![image](https://user-images.githubusercontent.com/76848066/104547298-28bd9500-5669-11eb-9199-f13ad06e7d61.png)


可以直接改JSON，两边是同步的。

可以找一个SSR,SSRoT的相应分享链接导入看一下，就知道相关字段在配置里怎么写了，还不明白的话可以看看源码。

**Comment by winXray** [comment]
SSRoT 只是多了几个参数，用的还是 SSR 的分享链接格式。

**Comment by zyp997** [comment]
@winXray 好的，非常感谢！
