### ISSUE TITLE
自动更新问题

### ISSUE THREAD

**Issue by StormS0** [winXray/winXray#1]
首先感谢作者的付出，这里提出一个问题，自动更新是否太随意了，没有询问是否更新就直接更新了新版本。

**Comment by winXray** [comment]
感觉你有些莫名其妙，
普通的修复BUG而已，还要一个个确认你不烦？！

什么叫没有询问？
winXray 开放了全部源码，不想更新你可以删掉更新代码，这还没有诚意？！

不满意可以自己修改，不然开源做什么？！
再不满意可以不要使用，有强制安装，强迫你使用？！
