### ISSUE TITLE
异常问题

### ISSUE THREAD

**Issue by liao6964799** [winXray/winXray#1]
有时候所有节点都会检测为异常,一些自己导入的正常节点有时候也会检测为异常不可用,但是用v2ray还是可以用

**Comment by winXray** [comment]
我都是正常的，你什么信息也没有提供，你说怎么办好？

**Comment by winXray** [comment]
1、确认先更新最新版本。
2、请提供可访问的 vmess 分享链接，稍后可以改下密码。

**Comment by winXray** [comment]
无法重现问题
