### ISSUE TITLE
建议用上geoip.dat

### ISSUE THREAD

**Issue by redstoneleo** [winXray/winXray#10]
原因：[https://qv2ray.net/plugins/v2ray-integration.html#为何不用-pac](https://qv2ray.net/plugins/v2ray-integration.html#为何不用-pac)

数据：
（1）https://github.com/v2ray/geoip
（2）https://github.com/Loyalsoldier/v2ray-rules-dat

主要是为了实现这个比较好用的功能：[https://qv2ray.net/getting-started/step5.html#调整路由方案](https://qv2ray.net/getting-started/step5.html#调整路由方案)

**Comment by gankang** [comment]
新东西：https://github.com/Hackl0us/GeoIP2-CN

**Comment by winXray** [comment]
没必要一个软件彭吹一下自己的实现方式，
就容不下其他的的软件选择不同的策略。世界应当容得下百花齐放。

IP路由不必要的把事情搞复杂了，你可以看看QV2ray带上V2ray体积40MB，
PAC更简洁 - 而且可以简单的随时调整、自由切换。

**Comment by redstoneleo** [comment]
Ok,尊重你的看法。
因为本软件用了自己的pac实现，还有没有方法继续用传统的pac文件呢？比如说我要如何才能用上这个传统的pac于本软件？
https://github.com/iBug/pac/releases/download/release-20201205/pac-17mon.txt

**Comment by huzy0909** [comment]
我觉得应该保持这种极简、又不失主流的基本功能、谨慎添加新功能，避免复杂、臃肿，因为大部分人真的用不到，仅是个人看法。

**Comment by winXray** [comment]
> Ok,尊重你的看法。
> 因为本软件用了自己的pac实现，还有没有方法继续用传统的pac文件呢？比如说我要如何才能用上这个传统的pac于本软件？
> https://github.com/iBug/pac/releases/download/release-20201205/pac-17mon.txt

PAC本来就允许不同的实现，各有各的写法，无所谓传统和标准。
winXray 是直接使用的 https://github.com/petronny/gfwlist2pac 该项目 812个star，
至于你发的 https://github.com/iBug/pac 仅79 star，我找不到使用这格式的理由。所以请按gfwlist2pac 的格式写

**Comment by redstoneleo** [comment]
PAC有统一的标准，但是允许不同的写法。

（1）我主要想问问这个项目能否支持标准文档里的写法 ？
https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file
因为我在本软件的编辑pac的文本框里没看到FindProxyForURL(url, host)这个函数

（2）https://github.com/iBug/pac 实际上是用来实现大陆和局域网IP走直连，此外的走代理，这个功能很有用，访问很多外网可以起到加速访问的作用。如果winXray允许这个pac规则那将再好不过，而一开始提到Qv2ray 也是因为它默认具备这个功能，只不过我还是希望有办法在winXray里实现同样的功能。
