### ISSUE TITLE
试图导入Trojan-Go代理服务器时配置文件报错

### ISSUE THREAD

**Issue by TsuyuzakiMahiru** [winXray/winXray#11]
导入如下配置
 ```
   {
        "address":"mydomain.com",
        "host":"mydomain.com",
        "id":"id",
        "network":"ws",
        "path":"/path",
        "port":"443",
        "protocol":"trojan-go",
        "ps":"trojan-go",
        "sni":"mydomain.com",
        "security":"none",
        "tls":"tls"
    }
```
后，双击运行后log提示

> A unified platform for anti-censorship.
> Failed to start: main: failed to read config files: [config.json] > infra/conf: failed to parse to outbound detour config. > json: cannot unmarshal string into Go struct field TrojanServerTarget.servers.port of type uint16

请教是何处有错误？谢谢！

**Comment by winXray** [comment]
"port":"443" 改为  "port":443 端口号去掉引号，一会我改进一下
