### ISSUE TITLE
如果服务器比较多，有些服务器不会进行延迟测试

### ISSUE THREAD

**Issue by ansemz** [winXray/winXray#11]
订阅的地址，有很多服务器，但是我发现下面的服务器不会测试速度。不知道是bug还是就是这么设计的？
[见图片](https://ftp.bmp.ovh/imgs/2020/12/cec06b4c94fe299e.png)

**Comment by winXray** [comment]
上次看到有人导入上千个服务器 - 所以新版限制了只检测前50个服务器。
如果50个服务器都找不到能用的，个人认为这个订阅地址是不是可以考虑换一换了？！
