### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by 314xsb** [winXray/winXray#12]
不要全部都选为 “ 允许被自动选为活动服务器  ”  最好添加一个选项， 可以让人直接在表内打勾。
活动服务器 全行高对比显示。

**Comment by winXray** [comment]
感谢反馈。

可以右键点服务器设置这个选项。
没有放到表里是因为这个选项并不常用，毕竟一个服务器的设置项太多都放到表里也会乱。 
也可以直接复制粘贴 "autoConnect":false 到服务器配置里。

最初活动服务器是高亮的，但点选也是高亮，所以后来取消了。

**Comment by dawei77778** [comment]
建议订阅节点和自建节点分开显示，类似小火箭的订阅节点叠加，类似我就是机场和自建一起用，有些机场订阅节点很多翻看很不方便

**Comment by winXray** [comment]
感谢反馈，后面会持续改进
