### ISSUE TITLE
公益节点都不可用，自己加的很多异常无法用

### ISSUE THREAD

**Issue by lin57112** [winXray/winXray#13]
公益节点都不可用，自己加的很多异常无法用

**Comment by winXray** [comment]
之前的公益节点已经换掉了，所以你用不了。
右键菜单里点「重置到默认服务器列表」更新一下就可以用了。
之前的公益节点，大家3天就用掉1TB流量，太滥用了所以不得不关。

至于自己加的很多异常，这应该是服务器有问题。
winXray会模拟浏览器做真实访问进行测试，如果服务器不可使用就会显示异常。
如果是判断错误，请提供服务器测试链接。

**Comment by winXray** [comment]
`vless://bf4a6c2b-db1b-57de-f45a-364aa254d1f7@z.vulvpstech.xyz:443/?flow=xtls-rprx-direct&host=z.vulvpstech.xyz&tls=xtls#%E7%BE%8E%E5%9B%BD%E8%A5%BF%E9%9B%85%E5%9B%BE_XTLS%2FDirect
vless://904da8f7-a5af-3c34-3f3d-c3b2ea59bde8@q.vulvpstech.xyz:443/?host=q.vulvpstech.xyz&tls=xtls#%E7%BE%8E%E5%9B%BD%E6%B4%9B%E6%9D%89%E7%9F%B6_XTLS%2FDirect`

也可以直接导入上面的vless分享链接
