### ISSUE TITLE
可否把“测速”和“自动连接”分开

### ISSUE THREAD

**Issue by clift190** [winXray/winXray#14]
一个机场80个节点，节点IP地址世界各地，“自动连接”在世界各地跳来跳去，非常不利于需要稳定IP地址的运用。但如果手动禁止自动测速并连接，又看不到每个节点的相应速度。建议全部默认自动测速，但设置一个按钮“自动连接最快”就好了。
另外，建议设置“传输速度”和“流量”栏信息。

**Comment by winXray** [comment]
你可以取消勾选「异常自动重连」，
本来就提供了这个选项，不是很明白你要表达的意思。

另外服务器跳来跳去，这本身就是因为服务器不稳定、访问异常，异常当然要换呀。
我用的服务器几个小时也不会跳。
