### ISSUE TITLE
求支持scoop安装

### ISSUE THREAD

**Issue by gankang** [winXray/winXray#14]
配置文件最好放在scoop专用目录，用于同步盘备份。

**Comment by winXray** [comment]
配置放到appData是目前桌面软件通行的做法，
如果需要同步备份，可以在「配置」界面右键导入导出JSON文件即可。

实际上也可以把JSON放到任意HTTP可以访问的网址，在 winXray 里可以一键导入。

**Comment by winXray** [comment]
也可以将配置保存到 \xray-core\winXray-default-servers.json 这个文件，
那么就可以直接放到网盘上同步，如果另一台电脑已经有配置, 只要右键「重置为默认服务器列表」就可以了。

**Comment by gankang** [comment]
可以，等有时间我去弄个scoop配置。

**Comment by buzhangjiuzhou** [comment]
@gankang 我简单弄了一个，https://github.com/buzhangjiuzhou/scoop-bzjz
但是我平时用的软件别的地方都有，所以里面只有这一个软件，笑。
