### ISSUE TITLE
请删除vless分享链接

### ISSUE THREAD

**Issue by Butterflyflower** [winXray/winXray#15]
vless还在测试中，后期有可能还会改动。vless开发者写明不要自定义分享链接。

**Comment by winXray** [comment]
首先请你区分清楚什么叫“定义分享链接规范”，
winXray从来没有定义过链接规范 - 链接规范是强制性要大家遵守的。
winXray只是临时做了个格式用来内部测试运行 - 没有要求任何支持或使用，官方标准出来，自然会做兼容和支持。

另外你说的那句话Xray官网上并没有看到。
v2ray文档曾经有相关的话写的是官方会在几个月前的某个版本中发布VLESS分享链接标准 - 但后来并没有发布，并且这句话打上了删除线 - 已经过期无效，我再去看了一下，这一段已经被删除，所以在你确认清楚以后再发。
