### ISSUE TITLE
添加更多节点的时候测试节点速度有bug

### ISSUE THREAD

**Issue by hans822418** [winXray/winXray#15]
![image](https://user-images.githubusercontent.com/67779256/101350240-9d165300-38c9-11eb-95b2-d027648c0873.png)
节点测试速度一半就停止了。

**Comment by winXray** [comment]
这个是限制了测试服务器的上限，没必要加载一大堆不能用的服务器吧？

**Comment by hans822418** [comment]
> 这个是限制了测试服务器的上限，没必要加载一大堆不能用的服务器吧？

这是订阅节点，应该可以全部开放测速吧？另外有Telegram群吗？这样反馈bug更快一点。

**Comment by hans822418** [comment]
> > 这个是限制了测试服务器的上限，没必要加载一大堆不能用的服务器吧？
> 
> 这是订阅节点，应该可以全部开放测速吧？另外有Telegram群吗？这样反馈bug更快一点。

有Telegram群吗？能加一个？
