### ISSUE TITLE
使用winXray一键安装Xray服务端时闪退

### ISSUE THREAD

**Issue by huzy0909** [winXray/winXray#16]
使用winXray一键安装Xray服务端时闪退，没有弹出输护密码对话框，操作系统windows10家庭中文版，以管理员身份运行winXray，也是一样的问题

**Comment by winXray** [comment]
你用的不是最新版吧？这个1.3.7应该就已经修复了。

**Comment by huzy0909** [comment]
我刚下载的，用的就是1.3.7版本

**Comment by winXray** [comment]
密码对话框都没出来，可能是你的端口号写错了。

**Comment by winXray** [comment]
有些服务器端口不是默认的端口要指定一下，在服务器后加冒号，后面写端口号，端口错了会直接关闭。

**Comment by huzy0909** [comment]
racknerd的vps，端口22，没错，格式你也是严格按winXray 提示格式填写

**Comment by huzy0909** [comment]
另一台搬瓦工vps也是同样的连接不上。

**Comment by winXray** [comment]
ssh是不会闪退的，
之前有说闪退是因为我误写了一句延时退出的代码 - 最新版已经删了。

打开就关了，如果不是输错了端口, 可能是VPS服务器阻止你登录了，你可以直接打开cmd输入 ssh登录试一下看下有没有错误信息。

**Comment by winXray** [comment]
测试了几台VPS都可以正常安装

**Comment by huzy0909** [comment]
VPS重新安装了一下，也是一样，感觉不是vps的问题，可能是我的电脑最近乱七八糟的安装了太多软件了

**Comment by winXray** [comment]
按 win+r 输入 cmd 回车，打开命令行。
然后输入 ssh root@你的服务器IP 然后回车，看显示什么。

**Comment by huzy0909** [comment]
找不到ssh文件

**Comment by huzy0909** [comment]
解决了，在设置、应用，可选功能里，把openssh客户端卸载，重新添加了一下，就好了，感谢！！

**Comment by winXray** [comment]
好的，感谢反馈。
