### ISSUE TITLE
全局代理打开国内网站很慢，pac用不了需要翻墙的软件，希望解决

### ISSUE THREAD

**Issue by woshinibb66** [winXray/winXray#18]

**Comment by woshinibb66** [comment]
写错了，是全局代理

**Comment by winXray** [comment]
只要系统没问题，
WIN7,WIN10都可以正常使用PAC模式。
你可以打开系统代理设置查看设置是否正确。

如果代理是可用的，PAC设置也是正确的。
可能正在使用其他软件冲突或损坏了系统，目前你提供的信息无法作进一步判断。

**Comment by woshinibb66** [comment]
我用pac模式的话，像TG我就打不开，如果我用全局模式，软件可以开了，但是国内某些网站由于节点原因就会打开的很慢。。

**Comment by winXray** [comment]
tg本来就不支持任何软件的PAC.
到端口设置里右键点SOCKS端口,复制代理地址 127.0.0.1:1080
然后到TG登录界面左下角，点击那个正在转圈圈的连接设置，粘贴到SOCKS代理里。

**Comment by woshinibb66** [comment]
谢谢
