### ISSUE TITLE
活动服务器：异常

### ISSUE THREAD

**Issue by mayuzhe** [winXray/winXray#2]
正常的节点导入订阅后却一直显示活动服务器

异常，不能用

**Comment by winXray** [comment]
你试一下 winXray 自带的节点应该正常的，订阅返回的必须是通用的分享链接格式，参考 winXray 自带的 https://justmysocks3.net/members/getsub.php?service=243238&id=d6eb5cd3-ddc7-4e62-8903-6ffaf958f6f8 或者你把订阅返回的内容发过来看一下，稍后你可以重置下密码。

xinXray连接后会模拟浏览器打开 google，如果无法访问google就会显示异常。如果有其他服务器会自动切换。

**Comment by mayuzhe** [comment]
可以直接邮箱发你吗？

winXray <notifications@github.com>于2020年11月29日 周日12:04写道：

**Comment by winXray** [comment]
不方便的话那把导入后生成的配置JSON发一下吧, 服务器地址与密码可以星号替代，另外导入的是哪个软件的订阅格式。

**Comment by mayuzhe** [comment]
方便，主要是学习一下怎么转换订阅？
http://subscribes.popocloud.xyz/link/195f9e419c2a4D
这是个一般的V2ray订阅。

winXray <notifications@github.com>于2020年11月29日 周日12:17写道：

**Comment by winXray** [comment]
测试了你发的订阅链接，
导入的服务器我这里都能正常使用，显示的都是「活动服务器 正常」
暂不清楚你那里是否有其他原因，是否hosts文件里指定了google.com的IP？

**Comment by mayuzhe** [comment]
谢谢，我再试试！😁

winXray <notifications@github.com>于2020年11月29日 周日12:31写道：

**Comment by mayuzhe** [comment]
老哥，我之前发错机场链接了，应该是这个：


https://sub.xn--9kq61slq0c.com/api/v1/client/subscribe?token=5064d4b3023ece811884754a69f7d369

这是个Trojan节点的clash订阅，这个我导入不能用。










winXray <notifications@github.com>于2020年11月29日 周日15:25写道：

**Comment by heartnn** [comment]
clash的肯定不能用啊，直接用clash啊

**Comment by winXray** [comment]
这种订阅连接是支持的，不能用是trojan的一个参数写错了，稍后会修正。

**Comment by mayuzhe** [comment]
哦哦，谢谢

winXray <notifications@github.com>于2020年12月1日 周二09:36写道：
