### ISSUE TITLE
https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/20201209.yml  打不开

### ISSUE THREAD

**Issue by lin57112** [winXray/winXray#2]
https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/20201209.yml  打不开，类似raw.githubusercontent.com我这都打不开，用别的代理软件都可以打开。

**Comment by winXray** [comment]
试了可以打开，请检查你是否修改了PAC配置，或者开启全局代理，个别域名打不开跟客户端界面应该没什么关系。

**Comment by winXray** [comment]
建议你运行一下 winXray 自带的 github 优化工具，一般可以修复这类问题，这个跟代理软件无关，而是你电脑DNS解析的问题。
