### ISSUE TITLE
被杀毒软件拦截

### ISSUE THREAD

**Issue by liao6964799** [winXray/winXray#2]
为什么啊?
![image](https://user-images.githubusercontent.com/35887374/102694980-8a076980-425f-11eb-8c2d-a495f2d0c468.png)

**Comment by winXray** [comment]
winXray是开源软件，绝不可能有病毒，至于你所用的杀毒软件为什么误报，我无法回答你，因为你用的杀毒软件不是我写的，而且你用的杀毒软件名字都没说。

建议你向杀毒软件厂商反馈。
