### ISSUE TITLE
一运行winXray.exe，就弹出提示框，且服务器都不能连接，不能代理上网 ，可以测速但不连接。没开其他的工具

### ISSUE THREAD

**Issue by dzm211** [winXray/winXray#20]
winxp系统，一运行winXray.exe，就弹出提示框
弹出提示框如下：https://upload.cc/i1/2020/12/11/yD7isW.jpg
请大神帮忙解决一下

**Comment by winXray** [comment]
这个不是 winXray 不支持 Windows XP, 
而是 XRray / V2Ray 核心不支持 Windows XP。
所以没有办法解决
