### ISSUE TITLE
导入的节点不能用

### ISSUE THREAD

**Issue by gankang** [winXray/winXray#20]
qv2ray，v2rayN都可以使用这个节点，winXray显示服务器异常不能上网。
    {
        "address":"104.20.61.183",
        "alterId":64,
        "host":"v2ray-vmess.3198688004.workers.dev",
        "id":"ad806487-2d26-4636-98b6-ab85cc8521f7",
        "network":"ws",
        "path":"/",
        "port":"443",
        "protocol":"vmess",
        "ps":"hku-v2ray-vmess",
        "security":"auto",
        "tls":"tls",
        "type":"none"
    }

**Comment by winXray** [comment]
请在配置里添加 `"sni":"v2ray-vmess.3198688004.workers.dev",`

完整配置：
```json
    {
        "address":"104.20.61.183",
        "alterId":64, 
        "concurrency":-1,
        "host":"v2ray-vmess.3198688004.workers.dev", 
        "sni":"v2ray-vmess.3198688004.workers.dev",
        "id":"ad806487-2d26-4636-98b6-ab85cc8521f7",
        "network":"ws",
        "path":"/",
        "port":"443",
        "protocol":"vmess",
        "ps":"hku-v2ray-vmess",
        "security":"auto",
        "tls":"tls",
        "type":"none"
    }
```

我稍后改一下默认设置

**Comment by gankang** [comment]
这样啊，qv里面有这个，v2rayN里面没看到。能否在服务器配置界面添加个将当前配置设置为默认服务器配置的功能？自动去更新那个文件。
