### ISSUE TITLE
希望可以增加测网速的功能

### ISSUE THREAD

**Issue by buzhangjiuzhou** [winXray/winXray#22]
现在的测速应该测的是延迟，但是有时候延迟低的网络并不一定好用，所以希望可以增加测网速的功能，并根据所测的网速来选择服务器，不过测网速就要走流量了，也是一个缺点，可以设置为可选项。

**Comment by winXray** [comment]
感谢反馈

**Comment by winXray** [comment]
winXray 我用了很久，测速一直很准，
以 justmysocks 为例，速度最快的是s3服务器，基本每次找到的最快的服务器都是 s3。

winXray 并不是以测速为目的，
而是需要在不消耗流量的情况上，以最快的速度在上百个服务器中找到最快的一个。

如果你需要更精细的测试服务器速度，请使用专门的测速工具。
