### ISSUE TITLE
更新后vless服务器出现不可用，活动服务器异常。Trojan服务器正常

### ISSUE THREAD

**Issue by doyle52150** [winXray/winXray#3]

**Comment by winXray** [comment]
未提供必要信息，无法重现问题

**Comment by winXray** [comment]
如果是 vless 启用了 xtls ，xtls 尚不稳定已弃用。

如果你想继续使用 xtls  可自行到 https://github.com/XTLS/Xray-core/releases/tag/v1.2.1 下载 xray.exe 覆盖 winXray 目录下的 v2ray_core/v2ray.exe 即可。

**Comment by doyle52150** [comment]
是启用了xtls，好的谢谢

**Comment by doyle52150** [comment]
是的，完美解决了问题，非常感谢！
