### ISSUE TITLE
部分订阅异常

### ISSUE THREAD

**Issue by kimi9999** [winXray/winXray#3]
不少机场的订阅链接，在winxray下无法订阅，但是放到小火箭上都可以正常订阅，为什么呢？？

**Comment by winXray** [comment]
请问很多机场具体指的是哪个机场呢?

提供的示例里各种格式的订阅都有, 在 winXray 里都能兼容:
[网络免费 vmess 服务器订阅链接](https://proxypool.ga/vmess/sub)   
[网络免费 Shadowsocks 服务器订阅链接](https://proxypool.ga/ss/sub)     
[网络免费 clash 服务器订阅链接](https://proxypoolss.tk/clash/proxies?speed=100&type=vmess,trojan)   

注意 winXray 不支持 ssr, 
如果你使用的是 win7, 可能有一些订阅链接你无法获取, 需要改下注册表启用系统 tls1.2 支持.

**Comment by kimi9999** [comment]
我说的是不少机场，可能用词不太准确，抱歉。
我用的4个机场3个有这样的问题，所以我也不太理解，而且有2个前几天还是好的，昨天开始就不正常了。今天升级到2.5还是有同样问题。
我电脑是win10，如果需要我可以私信你机场名

**Comment by winXray** [comment]
机场名字又不是分享链接，直接发一下吧。
不正常具体指的是什么不正常？！是分享链接没有获取到，还是说获取到分享链接以后，服务器连接不正常？！

然后具体什么代理协议不正常？vmess，ss, 还是 trojan?!
不正常的分享链接能否发一下( 密码或敏感信息可用 星号 代替 )。
 
另外我上面发的分享链接，有几千个不同协议，不同格式的分享链接，
你能否从中找出存在相同问题的分享链接？这样也方便分析原因。

**Comment by winXray** [comment]
无法重现问题。

**Comment by kimi9999** [comment]
popocloud.xyz泡泡云，vmess的，订阅没有获取的节点。同样的订阅链接，小火箭上可以订阅更新会有30个左右的节点，winxray上订阅只出了1个是剩余流量的无效节点。
我没有加vmess的节点链接这样去试，我可以去试试

还有2个站我看了，是我搞错了，SSR的，抱歉

**Comment by kimi9999** [comment]
单独加vmess链接是好的。。。

**Comment by winXray** [comment]
大概知道原因了，稍后修复，感谢反馈。
