### ISSUE TITLE
配置文件路径错误

### ISSUE THREAD

**Issue by xixiri** [winXray/winXray#3]
2020/12/22 08:49:22 [Info] main/jsonem: Reading config: E:\杞欢\v2ray\winXray\xray-core\config.json

日志区出现这个，我电脑里没这个目录啊

**Comment by winXray** [comment]
这个是回显的时候编码错误，实际上已经正确读取了配置文件，应当能正常运行了吧？！

**Comment by xixiri** [comment]
可以运行，不错

**Comment by winXray** [comment]
已改进，感谢反馈。
