### ISSUE TITLE
卡巴斯基扫描好像有病毒

### ISSUE THREAD

**Issue by dkdobe** [winXray/winXray#3]
winXray.7z//winXray.exe;检测到恶意对象;检测到;VHO:Trojan-Downloader.MSIL.Convagent.gen;D:\Downloads\winXray.7z//winXray.exe;D:\Downloads\winXray.7z//winXray.exe;文件;活动用户;云保护;木马程序;高;启发式分析;检测到;今天，2020/12/22 19:00

**Comment by winXray** [comment]
开源软件不可能有病毒，建议更换杀毒软件。

**Comment by aardio** [comment]
到卡巴斯基官方检测了 winXray 2.1 版本，显示文件安全没有病毒，所以无法提交误报。

之前也试过，有的版本检测有病毒，有时候改几句代码又莫名其妙说没有病毒，这么多杀毒软件，没精力天天跟他们折腾，不放心自己拿源码编译下使用吧。
