### ISSUE TITLE
不使用代理模式，用winXray做tor的前置代理失败

### ISSUE THREAD

**Issue by gankang** [winXray/winXray#3]
Qv2ray和v2rayN测试同一个的节点均可使用。
![image](https://user-images.githubusercontent.com/62201630/101802644-a4985f00-3b4a-11eb-9db1-aaeb85e3b5fb.png)

**Comment by winXray** [comment]
如果你的SOCKS,HTTP代理可以正常使用,个别软件无法连接,请检查这些软件的配置,我不使用TOR,所以无法重现你的问题.
