### ISSUE TITLE
Telegram客户端好像没法连接

### ISSUE THREAD

**Issue by lostkf** [winXray/winXray#4]
没SOCKS5或HTTP？代理服务器端口和PAC端口都没用，全局代理倒是OK

**Comment by winXray** [comment]
全局代理就是SOCKS5代理（HTTP代理下版会加上），Telegram用PAC不行是因为他使用的一些IP没有加到PAC配置里。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ULO"<notifications@github.com&gt;; 
发送时间: 2020年12月2日(星期三) 下午2:33
收件人: "winXray/winXray"<winXray@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [winXray/winXray] Telegram客户端好像没法连接 (#4)





 
没SOCKS5或HTTP？代理服务器端口和PAC端口都没用，全局代理倒是OK
