### ISSUE TITLE
winxray1.2在win10中报毒哦，

### ISSUE THREAD

**Issue by yzyz5840** [winXray/winXray#5]
试用了一下winxray1.1.没有啥问题，看见出了1.2的下载试用win10直接报毒

**Comment by winXray** [comment]
放心开源软件不会有病毒的，WIN10提交验证需要一点时间，一般过一两天就不会再报了。

**Comment by yzyz5840** [comment]
哦，还在试用，挺方便的， 用QV的时候，电报不需要设置直接联系 ，用这个的时候，需要设置一下代理才能连接，

**Comment by winXray** [comment]
感谢反馈，那个暂时可以使用Xray/V2ray自带的IP路由配置，参考官网文档
