### ISSUE TITLE
现在无法下载了

### ISSUE THREAD

**Issue by travelstone** [winXray/winXray#5]
麻烦查看一下，谢谢。IDM一直提示“无法分配请求的地址。改地址无效。”

**Comment by winXray** [comment]
没怎么明白你指的具体问题。
你是想说自带的免费服务器用不了？！我试了可以用，如果你用不了，建议换成自己的服务器。
如果浏览器可以正常上网，检查一下你IDM的配置。

**Comment by travelstone** [comment]
是我没表达清楚。不是服务器的问题，是您这个winxray的软件包下载不了。 @winXray

**Comment by winXray** [comment]
我试了一下，一直可以下载呀，
请运行一下 winXray 的  github 优化工具，这工具能自动修复访问不了raw.githubusercontent.com的问题。

**Comment by travelstone** [comment]
修改了一下hosts文件，可以访问raw.githubusercontent.com并下载了，谢谢
