### ISSUE TITLE
能不能设置不自动切换节点

### ISSUE THREAD

**Issue by xixiri** [winXray/winXray#6]
有些时候我需要自主选择节点啊，比如我要使用特定国家的节点来打游戏什么的。目前是我选择上一会就自己跑了，clash也可以选择特定节点和自动选择都可以啊

**Comment by winXray** [comment]
主界面取消勾选  「异常自动重连」，不难找吧？！
建议升级到最新版，一般切换是因为服务器不稳定，winXray会模拟浏览器自动访问网页，如果重试多次无法连接就会自动切换。
