### ISSUE TITLE
使用上的一些建议和问题

### ISSUE THREAD

**Issue by zyp997** [winXray/winXray#6]
很谢谢作者能够编写一个这样的软件，解决了不少麻烦。下面是我想提出的一些建议和问题
1.能够增加一个开机自启选项吗？
2.客户端最小化和关闭都是会放到托盘下，能修改一下吗？最小化放到任务栏，关闭放到托盘下。还有就是再次点击在任务栏的客户端也会放到托盘下。使用起来有点别扭。
3.使用链接导入trojan-go节点，在连接时全部都是显示活动服务器异常，但是是能够正常使用的。

**Comment by winXray** [comment]
感谢建议，说得有道理，后面会改进，trojan-go显示异常的可以发个测试链接吗？ 或者告诉我是哪个机场的链接也行。

**Comment by zyp997** [comment]
可以，我之后改下配置就好了。
trojan-go://8f91b6a0-e8ee-11ea-adc1-0242ac120002@104.25.92.172:443/?type=ws&sni=heroku-eu.proxy-js.workers.dev&host=heroku-eu.proxy-js.workers.dev&path=%2F8f91b6a0-e8ee-11ea-adc1-0242ac120002-trojan#heroku-eu(Trojan-go)

**Comment by winXray** [comment]
配置改了哪好了？！

**Comment by zyp997** [comment]
什么意思？难道说我放错链接了。。
json配置是这样的：
   {
        "address":"104.25.92.172",
        "host":"heroku-eu.proxy-js.workers.dev",
        "id":"8f91b6a0-e8ee-11ea-adc1-0242ac120002",
        "network":"ws",
        "path":"/8f91b6a0-e8ee-11ea-adc1-0242ac120002-trojan",
        "port":443,
        "protocol":"trojan-go",
        "ps":"heroku-eu(Trojan-go)",
        "sni":"heroku-eu.proxy-js.workers.dev",
        "tls":"tls"
    },

**Comment by winXray** [comment]
v1.3 应当修复了上述问题，你再试试看，感谢反馈。
