### ISSUE TITLE
用virustotal.com检测，红色警报有点多

### ISSUE THREAD

**Issue by jacklee789** [winXray/winXray#7]
希望winxray继续优化，将virustotal.com检测的红色警报降到少于5个

**Comment by winXray** [comment]
不知道为什么老问这个问题，
winXray 是开源软件，怎么可能会有病毒?!开源还不放心那要怎么整呢？

现在随便写个空白EXE，误报都比 winXray 多，而且他们基本是新EXE就误报，winXray更新频繁，我不可能一个个的去提交那么多杀毒厂商。我换另外一个客户端，启动报毒，，每切换一次代理就报一次毒，网银U盾报毒，winXray 就很安静报毒很少，优化得够可以了吧？！

遇到这个问题：
请自行提交误报检测 ，
如果你用的杀毒软件没有提交误报的功能，建议换一个。
或者自行添加到白名单 ，如果你用的杀毒软件没有这功能，建议换一个。
如果实在不放心，提供了源代码可以自行编译。

**Comment by jacklee789** [comment]
v2rayn和qv2ray都是通过Releases发布软件版本升级，winXray的软件发布方式与它们很不同，容易导致小白出现迷惑误解。希望winXray通过Releases发布软件版本升级。

**Comment by winXray** [comment]
直接点下载明显是更简单？！
