### ISSUE TITLE
检查更新出错以及github网速优化导致GitHub上不了

### ISSUE THREAD

**Issue by zyp997** [winXray/winXray#8]
RT
<img width="603" alt="微信截图_20201211161716" src="https://user-images.githubusercontent.com/53375741/101880205-7dcf3c80-3bcd-11eb-8401-b70e7cd64020.png">
还有就是github网速优化，修改host之后导致github直接上不了了。

**Comment by huzy0909** [comment]
同样遇到这样的情况

**Comment by winXray** [comment]
国内这个域名基本就是连不上的，优化了以后可以解析到正确IP，我试过一直是可以解决问题的。

但如果说你优化以后反而连不上了，解决方法简单，工具上有打开HOST文件的链接，打开以后，直接删掉这个域名就恢复默认了。

**Comment by zyp997** [comment]
@winXray 那可以考虑一下直接使用代理进行更新xray内核和winxray吗？

**Comment by huzy0909** [comment]
> @winXray 那可以考虑一下直接使用代理进行更新xray内核和winxray吗？
> 我刚刚又试了一下优化改了host，貌似是筛选出来的IP问题，换一个ip就可以了。更新和上GitHub都成功了。

咱本身就是个代理软件，我觉用代理会更好一些

**Comment by winXray** [comment]
raw.githubusercontent.com 默认就是走代理的，但手动更新PAC可能会删除 raw.githubusercontent.com，
github 有些IP可能访问有问题。
