### ISSUE TITLE
使用tg时连接不上

### ISSUE THREAD

**Issue by zyp997** [winXray/winXray#9]
<img width="536" alt="微信截图_20201205202050" src="https://user-images.githubusercontent.com/53375741/101242900-89d37e00-3737-11eb-9c76-bde27f5786d2.png">
<img width="765" alt="微信截图_20201205202126" src="https://user-images.githubusercontent.com/53375741/101242902-8c35d800-3737-11eb-87a7-5f8e18ace089.png">
<img width="689" alt="微信截图_20201205202140" src="https://user-images.githubusercontent.com/53375741/101242903-8d670500-3737-11eb-96d4-8277ea4169a0.png">
上youtube和Google是没问题的，上telegram就提示一直在连接中。即使是你提供的公益节点也会这样。
使用之前的版本好像是没问题的，最新版的会有这个问题。

**Comment by winXray** [comment]
你上面截图应当比较清楚，你当前的活动连接是你自己添加的服务器，并不是 winXray提供的服务器，跟 winXray 版本升级应当没有关系。

**Comment by zyp997** [comment]
喔喔，不好意思，应该是我这边的问题。
